#pragma once
#include <vector>

/**
 * @brief Class to store each nurse actual workload generated by patients on given day and shift and here maximum workload on given day and shift. 
 * Based on it the soft restrictions if nurse is overworked is calculated
*/
class NurseWorkload
{
public:
	NurseWorkload() = default;
	NurseWorkload(std::vector<int> actual, std::vector<int> max);

	void setActualWorkload(std::vector<int>&& actualWorkload);
	void setMaximumWorkload(std::vector<int>&& maximumWorkload);

	std::vector<int>& actualWorkload();
	std::vector<int>& maximumWorkload();

private:
	std::vector<int> _actualWorkload;
	std::vector<int> _maximumWorkload;
};